## Khai Thác Dữ Liệu _ Tuần 1

#### 20280071 - Nguyễn Tiến Phong

In [61]:
# Đọc thư viện và module
import pandas as pd
import numpy as np

## Đọc dữ liệu từ đường dẫn :

In [75]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/arrhythmia/arrhythmia.data"
df = pd.read_csv(url, header=None)

In [76]:
df.head()

0    1    2    3    4    5    6    7    8    9    ...  270   271  272  273  \
0   75    0  190   80   91  193  371  174  121  -16  ...  0.0   9.0 -0.9  0.0   
1   56    1  165   64   81  174  401  149   39   25  ...  0.0   8.5  0.0  0.0   
2   54    0  172   95  138  163  386  185  102   96  ...  0.0   9.5 -2.4  0.0   
3   55    0  175   94  100  202  380  179  143   28  ...  0.0  12.2 -2.2  0.0   
4   75    0  190   80   88  181  360  177  103  -16  ...  0.0  13.1 -3.6  0.0   

   274  275  276   277   278  279  
0  0.0  0.9  2.9  23.3  49.4    8  
1  0.0  0.2  2.1  20.4  38.8    6  
2  0.0  0.3  3.4  12.3  49.0   10  
3  0.0  0.4  2.6  34.6  61.6    1  
4  0.0 -0.1  3.9  25.4  62.8    7  

[5 rows x 280 columns]

In [77]:
df.tail()

0    1    2    3    4    5    6    7    8    9    ...  270   271   272  \
447   53    1  160   70   80  199  382  154  117  -37  ...  0.0   4.3  -5.0   
448   37    0  190   85  100  137  361  201   73   86  ...  0.0  15.6  -1.6   
449   36    0  166   68  108  176  365  194  116  -85  ...  0.0  16.3 -28.6   
450   32    1  155   55   93  106  386  218   63   54  ... -0.4  12.0  -0.7   
451   78    1  160   70   79  127  364  138   78   28  ...  0.0  10.4  -1.8   

     273  274  275  276   277   278  279  
447  0.0  0.0  0.7  0.6  -4.4  -0.5    1  
448  0.0  0.0  0.4  2.4  38.0  62.4   10  
449  0.0  0.0  1.5  1.0 -44.2 -33.2    2  
450  0.0  0.0  0.5  2.4  25.0  46.6    1  
451  0.0  0.0  0.5  1.6  21.3  32.8    1  

[5 rows x 280 columns]

#### Tính toán các thống kê cơ bản

In [78]:
df.describe()

0           1           2           3           4           5    \
count  452.000000  452.000000  452.000000  452.000000  452.000000  452.000000   
mean    46.471239    0.550885  166.188053   68.170354   88.920354  155.152655   
std     16.466631    0.497955   37.170340   16.590803   15.364394   44.842283   
min      0.000000    0.000000  105.000000    6.000000   55.000000    0.000000   
25%     36.000000    0.000000  160.000000   59.000000   80.000000  142.000000   
50%     47.000000    1.000000  164.000000   68.000000   86.000000  157.000000   
75%     58.000000    1.000000  170.000000   79.000000   94.000000  175.000000   
max     83.000000    1.000000  780.000000  176.000000  188.000000  524.000000   

              6           7           8           9    ...         270  \
count  452.000000  452.000000  452.000000  452.000000  ...  452.000000   
mean   367.207965  169.949115   90.004425   33.676991  ...   -0.278982   
std     33.385421   35.633072   25.826643   45.431434  ...    0.548876   
min    232.000000  108.000000    0.000000 -172.000000  ...   -4.100000   
25%    350.000000  148.000000   79.000000    3.750000  ...   -0.425000   
50%    367.000000  162.000000   91.000000   40.000000  ...    0.000000   
75%    384.000000  179.000000  102.000000   66.000000  ...    0.000000   
max    509.000000  381.000000  205.000000  169.000000  ...    0.000000   

              271         272         273    274         275         276  \
count  452.000000  452.000000  452.000000  452.0  452.000000  452.000000   
mean     9.048009   -1.457301    0.003982    0.0    0.514823    1.222345   
std      3.472862    2.002430    0.050118    0.0    0.347531    1.426052   
min      0.000000  -28.600000    0.000000    0.0   -0.800000   -6.000000   
25%      6.600000   -2.100000    0.000000    0.0    0.400000    0.500000   
50%      8.800000   -1.100000    0.000000    0.0    0.500000    1.350000   
75%     11.200000    0.000000    0.000000    0.0    0.700000    2.100000   
max     23.600000    0.000000    0.800000    0.0    2.400000    6.000000   

              277         278         279  
count  452.000000  452.000000  452.000000  
mean    19.326106   29.473230    3.880531  
std     13.503922   18.493927    4.407097  
min    -44.200000  -38.600000    1.000000  
25%     11.450000   17.550000    1.000000  
50%     18.100000   27.900000    1.000000  
75%     25.825000   41.125000    6.000000  
max     88.800000  115.900000   16.000000  

[8 rows x 275 columns]

#### Thay thế các dấu *?* bằng giá trị *np.NaN*

In [79]:
df = df.replace('?', np.NaN)

#### Chuyển tập dữ liệu thành ma trận

In [80]:
array = df.values
array

array([[75, 0, 190, ..., 23.3, 49.4, 8],
       [56, 1, 165, ..., 20.4, 38.8, 6],
       [54, 0, 172, ..., 12.3, 49.0, 10],
       ...,
       [36, 0, 166, ..., -44.2, -33.2, 2],
       [32, 1, 155, ..., 25.0, 46.6, 1],
       [78, 1, 160, ..., 21.3, 32.8, 1]], dtype=object)

#### Nhập thêm thư viện StandardScaler và MinMaxScaler của thư viện sklearn.preprocessing

In [81]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

## Thực hiện chuẩn hóa

#### Chuẩn hóa theo StandardScaler

In [82]:
data_scaler = StandardScaler()
scale = data_scaler.fit_transform(array)
scale

array([[ 1.73443926, -1.1075202 ,  0.64132669, ...,  0.29460309,
         1.07867028,  0.93577103],
       [ 0.57931213,  0.90291807, -0.03199781, ...,  0.0796127 ,
         0.50487408,  0.4814547 ],
       [ 0.4577198 , -1.1075202 ,  0.15653305, ..., -0.52087767,
         1.0570176 ,  1.39008736],
       ...,
       [-0.63661117, -1.1075202 , -0.00506483, ..., -4.7094834 ,
        -3.3926096 , -0.42717797],
       [-0.87979583,  0.90291807, -0.30132761, ...,  0.42063193,
         0.92710147, -0.65433613],
       [ 1.91682776,  0.90291807, -0.16666271, ...,  0.14633386,
         0.18008377, -0.65433613]])

#### Chuẩn hóa theo MinMaxScaler

In [83]:
data_scaler = MinMaxScaler()
scale = data_scaler.fit_transform(array)
scale

array([[0.90361446, 0.        , 0.12592593, ..., 0.5075188 , 0.56957929,
        0.46666667],
       [0.6746988 , 1.        , 0.08888889, ..., 0.48571429, 0.50097087,
        0.33333333],
       [0.65060241, 0.        , 0.09925926, ..., 0.42481203, 0.56699029,
        0.6       ],
       ...,
       [0.43373494, 0.        , 0.09037037, ..., 0.        , 0.03495146,
        0.06666667],
       [0.38554217, 1.        , 0.07407407, ..., 0.52030075, 0.55145631,
        0.        ],
       [0.93975904, 1.        , 0.08148148, ..., 0.4924812 , 0.46213592,
        0.        ]])

## Equi-width ranges :

In [84]:
min_value  = int(np.floor(df.min().min()))
max_value = int(np.ceil(df.max().max()))
num_bins = 10 # số bins
wrange = max_value - min_value
ivalue = int(np.ceil(wrange/10)) # (max - min)/ số bins
ivalue

C:\Users\USER\AppData\Local\Temp/ipykernel_18648/797109157.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  min_value  = int(np.floor(df.min().min()))
C:\Users\USER\AppData\Local\Temp/ipykernel_18648/797109157.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  max_value = int(np.ceil(df.max().max()))


103

In [85]:
for i in range(1, num_bins+1):
    intervals = [min_value + (i-1)*ivalue, min_value + i*ivalue]
    print("Bin" + str(i) + " = ", intervals)

Bin1 =  [-243, -140]
Bin2 =  [-140, -37]
Bin3 =  [-37, 66]
Bin4 =  [66, 169]
Bin5 =  [169, 272]
Bin6 =  [272, 375]
Bin7 =  [375, 478]
Bin8 =  [478, 581]
Bin9 =  [581, 684]
Bin10 =  [684, 787]


## Equi-depth ranges:

In [86]:
arr = df.values
arr = arr.astype(dtype=float)
arr.sort()

In [87]:
num_bins = 10 # số bins
n = len(arr) 
ivalue = int(np.round(n/num_bins)) # chiều dài data / số bins
for i in range(1, num_bins+1):
    intervals = [] # khởi tạo bin
    for j in range(i*ivalue, (i+1)*ivalue):
        if j >= n:
            break
        intervals.append(arr[j]) # thêm phần tử vào bins
    #print(intervals)
    print("Bin" + str(i) + " : ", len(intervals)) # in ra số giá trị của mỗi bin

Bin1 :  45
Bin2 :  45
Bin3 :  45
Bin4 :  45
Bin5 :  45
Bin6 :  45
Bin7 :  45
Bin8 :  45
Bin9 :  45
Bin10 :  2


# 2. PCA

### 1. Chuẩn bị dữ liệu

In [89]:
# Nhập thư viện
import numpy as np
import pandas as pd

In [90]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/musk/clean1.data.Z"
# vì file clean1.data.Z không đọc được nên em đọc file clean1.data luôn
df = pd.read_csv("D:\Kì 6\Khai thác dữ liệu\clean1.data", header=None)

In [91]:
df.head()

0        1    2    3    4    5    6    7    8    9    ...  159  160  \
0  MUSK-188  188_1+1   42 -198 -109  -75 -117   11   23  -88  ...  -74 -129   
1  MUSK-188  188_1+2   42 -191 -142  -65 -117   55   49 -170  ... -302   60   
2  MUSK-188  188_1+3   42 -191 -142  -75 -117   11   49 -161  ...  -73 -127   
3  MUSK-188  188_1+4   42 -198 -110  -65 -117   55   23  -95  ... -302   60   
4  MUSK-190  190_1+1   42 -198 -102  -75 -117   10   24  -87  ...  -73 -127   

   161  162  163  164  165  166  167  168  
0 -120  -38   30   48  -37    6   30  1.0  
1 -120  -39   31   48  -37    5   30  1.0  
2 -120  -38   30   48  -37    5   31  1.0  
3 -120  -39   30   48  -37    6   30  1.0  
4   51  128  144   43  -30   14   26  1.0  

[5 rows x 169 columns]

In [92]:
# Xóa 2 cột đầu là kiểu chuỗi không thể tính toán
df_v2 = df.drop(df.columns[[0, 1]], axis=1)
df_v2.head()

2    3    4    5    6    7    8    9    10   11   ...  159  160  161  162  \
0   42 -198 -109  -75 -117   11   23  -88  -28  -27  ...  -74 -129 -120  -38   
1   42 -191 -142  -65 -117   55   49 -170  -45    5  ... -302   60 -120  -39   
2   42 -191 -142  -75 -117   11   49 -161  -45  -28  ...  -73 -127 -120  -38   
3   42 -198 -110  -65 -117   55   23  -95  -28    5  ... -302   60 -120  -39   
4   42 -198 -102  -75 -117   10   24  -87  -28  -28  ...  -73 -127   51  128   

   163  164  165  166  167  168  
0   30   48  -37    6   30  1.0  
1   31   48  -37    5   30  1.0  
2   30   48  -37    5   31  1.0  
3   30   48  -37    6   30  1.0  
4  144   43  -30   14   26  1.0  

[5 rows x 167 columns]

In [93]:
# Tính toán thống kê cơ bản
df_v2.describe()

2           3           4           5           6           7    \
count  476.000000  476.000000  476.000000  476.000000  476.000000  476.000000   
mean    38.731092 -120.142857  -79.243697   15.903361 -112.298319   -9.760504   
std     18.087948   88.313464   69.172519   75.515959   28.704947   92.025496   
min     -9.000000 -199.000000 -166.000000 -115.000000 -117.000000 -184.000000   
25%     31.000000 -193.000000 -144.000000  -53.000000 -117.000000  -89.000000   
50%     42.000000 -144.500000 -108.000000   28.000000 -117.000000   11.000000   
75%     50.000000 -101.000000  -21.000000   38.000000 -117.000000   70.250000   
max    130.000000   98.000000   83.000000  157.000000  238.000000  200.000000   

              8           9           10          11   ...         159  \
count  476.000000  476.000000  476.000000  476.000000  ...  476.000000   
mean   -16.628151    7.762605  -91.048319  -76.077731  ... -204.405462   
std    106.560891   75.786461   96.321303   72.467693  ...   89.566426   
min   -170.000000 -231.000000 -242.000000 -284.000000  ... -324.000000   
25%   -159.000000   -9.250000 -215.000000 -118.250000  ... -264.000000   
50%     41.000000   18.000000  -41.000000  -73.500000  ... -236.000000   
75%     51.000000   57.000000  -30.000000  -28.000000  ... -154.750000   
max    214.000000  188.000000  135.000000  218.000000  ...   72.000000   

              160         161         162         163         164         165  \
count  476.000000  476.000000  476.000000  476.000000  476.000000  476.000000   
mean  -108.262605  -25.231092   37.428571   79.752101   85.363445  -34.128151   
std    121.794583   65.588295   87.315888   49.269244   47.487575   16.019277   
min   -217.000000 -135.000000 -126.000000  -78.000000   35.000000 -132.000000   
25%   -208.000000  -91.000000  -39.250000   33.000000   54.000000  -42.250000   
50%   -189.500000  -15.000000   31.500000   84.000000   69.000000  -36.000000   
75%     30.000000   22.000000  128.000000  119.000000   99.000000  -28.000000   
max    173.000000  185.000000  253.000000  291.000000  302.000000   24.000000   

              166         167         168  
count  476.000000  476.000000  476.000000  
mean   -26.241597   33.714286    0.434874  
std     58.009205   54.189087    0.496262  
min   -258.000000  -72.000000    0.000000  
25%    -28.000000  -12.000000    0.000000  
50%    -11.000000   35.000000    0.000000  
75%      7.000000   74.000000    1.000000  
max     82.000000  235.000000    1.000000  

[8 rows x 167 columns]

In [94]:
# Chuyển dữ liệu sang ma trận
arr = df_v2.values
arr

array([[  42., -198., -109., ...,    6.,   30.,    1.],
       [  42., -191., -142., ...,    5.,   30.,    1.],
       [  42., -191., -142., ...,    5.,   31.,    1.],
       ...,
       [  43., -102.,  -20., ...,  -19.,  -36.,    0.],
       [  39.,  -58.,   27., ...,    3.,   74.,    0.],
       [  52., -121.,  -24., ...,   12.,   96.,    0.]])

### 2. Tính mean và lấy từng phần tử của ma trận trừ mean

In [95]:
mean = np.mean(arr, axis=0)
arr = arr - mean
arr

array([[  3.26890756, -77.85714286, -29.75630252, ...,  32.24159664,
         -3.71428571,   0.56512605],
       [  3.26890756, -70.85714286, -62.75630252, ...,  31.24159664,
         -3.71428571,   0.56512605],
       [  3.26890756, -70.85714286, -62.75630252, ...,  31.24159664,
         -2.71428571,   0.56512605],
       ...,
       [  4.26890756,  18.14285714,  59.24369748, ...,   7.24159664,
        -69.71428571,  -0.43487395],
       [  0.26890756,  62.14285714, 106.24369748, ...,  29.24159664,
         40.28571429,  -0.43487395],
       [ 13.26890756,  -0.85714286,  55.24369748, ...,  38.24159664,
         62.28571429,  -0.43487395]])

### 3. Tìm ma trận hiệp phương sai

In [96]:
cov = arr.T.dot(arr)/arr.shape[0]
cov

array([[ 3.26486512e+02,  3.02465786e+02,  3.30419762e+02, ...,
         1.28130411e+02, -9.32196879e+01,  2.26184591e-01],
       [ 3.02465786e+02,  7.78288295e+03,  4.57761014e+03, ...,
        -9.32307623e+02,  4.33524310e+02, -6.63745498e+00],
       [ 3.30419762e+02,  4.57761014e+03,  4.77478515e+03, ...,
        -4.95773162e+02, -7.00885354e+01, -4.05998870e+00],
       ...,
       [ 1.28130411e+02, -9.32307623e+02, -4.95773162e+02, ...,
         3.35799835e+03, -1.93487095e+02,  7.28783719e+00],
       [-9.32196879e+01,  4.33524310e+02, -7.00885354e+01, ...,
        -1.93487095e+02,  2.93028812e+03, -1.70138055e+00],
       [ 2.26184591e-01, -6.63745498e+00, -4.05998870e+00, ...,
         7.28783719e+00, -1.70138055e+00,  2.45758598e-01]])

### 4. Tính trị riêng, vector riêng

In [97]:
from numpy.linalg import eig
eigen_values, eigen_vectors = eig(cov)

In [98]:
eigen_values

array([4.52287400e+05, 1.44449707e+05, 7.76471611e+04, 6.22047486e+04,
       4.89749648e+04, 4.66236599e+04, 3.06137217e+04, 2.35593275e+04,
       1.81350704e+04, 1.72082147e+04, 1.41487016e+04, 1.28562182e+04,
       1.22668538e+04, 9.85310881e+03, 9.11872497e+03, 8.54204801e+03,
       7.58193306e+03, 7.09519908e+03, 6.78996646e+03, 6.29616245e+03,
       5.88618435e+03, 5.43650931e+03, 5.21502089e+03, 4.79681960e+03,
       4.26382539e+03, 4.09138807e+03, 3.78843345e+03, 3.64595774e+03,
       3.41863008e+03, 3.12591110e+03, 2.94390442e+03, 2.68589929e+03,
       2.47515540e+03, 2.42237918e+03, 2.33375165e+03, 2.10757061e+03,
       1.99891575e+03, 1.83520454e+03, 1.74278156e+03, 1.61469538e+03,
       1.55685395e+03, 1.42850060e+03, 1.37307886e+03, 1.29917244e+03,
       1.17902277e+03, 1.13795492e+03, 1.06544728e+03, 9.91612201e+02,
       9.78094330e+02, 9.15815204e+02, 8.67091592e+02, 8.12278489e+02,
       7.90448798e+02, 7.24285230e+02, 7.64667345e+02, 7.45405248e+02,
      

In [99]:
eigen_vectors

array([[-6.07485609e-03, -5.92762276e-04,  2.15462225e-02, ...,
        -7.84264403e-02, -4.92105501e-02, -4.10619715e-03],
       [-5.91429279e-02, -2.37599886e-02,  2.07846036e-01, ...,
        -6.49047565e-02, -4.11349307e-02,  2.73674847e-02],
       [-6.62868507e-02, -1.79219141e-03,  1.30939236e-01, ...,
         2.23440424e-01,  1.86877294e-01, -6.12186091e-02],
       ...,
       [-1.59190069e-03,  1.69781949e-02,  1.94359239e-02, ...,
        -4.12916437e-02,  1.31564334e-02, -3.43709984e-02],
       [ 7.30081635e-03, -7.01984362e-03,  5.28802614e-02, ...,
         5.65212662e-03,  1.23256710e-02,  4.55003733e-02],
       [ 6.40934800e-05,  4.13478702e-05, -1.26313612e-04, ...,
         1.11997348e-03, -5.52298271e-04,  1.40411795e-03]])

### 5. Chọn k giá trị riêng lớn nhất để tạo ma trận U

In [100]:
k = 20 # chọn k = 20
select_index = np.argsort(eigen_values)[::-1][:k]
U = eigen_vectors[:, select_index]

In [101]:
U

array([[-6.07485609e-03, -5.92762276e-04,  2.15462225e-02, ...,
        -2.98889156e-02,  1.18230766e-02, -2.45226211e-02],
       [-5.91429279e-02, -2.37599886e-02,  2.07846036e-01, ...,
         3.21566299e-02, -1.22018779e-02,  9.68714674e-02],
       [-6.62868507e-02, -1.79219141e-03,  1.30939236e-01, ...,
        -2.48058262e-02, -3.08017614e-02, -2.18609227e-02],
       ...,
       [-1.59190069e-03,  1.69781949e-02,  1.94359239e-02, ...,
         1.42668395e-01,  1.49582032e-01, -4.12745327e-02],
       [ 7.30081635e-03, -7.01984362e-03,  5.28802614e-02, ...,
        -2.86090617e-02, -4.05220182e-02, -1.98151781e-03],
       [ 6.40934800e-05,  4.13478702e-05, -1.26313612e-04, ...,
        -2.23402956e-04,  7.09687719e-04,  2.66104435e-04]])

### 6. Ánh xạ dữ liệu sang không gian mới

In [102]:
arr_new = arr.dot(U)
arr_new

array([[ -118.66633316,  -750.09738989,  -214.33833157, ...,
         -102.44164268,    83.8731755 ,    27.21559193],
       [ -133.54573115,  -757.1459322 ,  -187.45864638, ...,
          132.80528519,   -95.94762959,   -40.23821229],
       [  -52.86376978,  -730.14646419,  -166.73413371, ...,
          -61.13253037,    99.80841644,   -13.59812287],
       ...,
       [-1015.0434911 ,   205.9643209 ,  -263.29585599, ...,
          230.18266326,    39.26863635,    -5.66365261],
       [  461.08172523,     5.92444748,   600.04591703, ...,
           21.51059785,    66.38581559,  -137.3936217 ],
       [-1012.07888605,   190.68338112,   -39.42448442, ...,
          163.80074577,    72.8110053 ,   -84.66641363]])

## PCA bằng thư viện sklearn

In [103]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [104]:
# Chuẩn hóa dữ liệu
scaler = StandardScaler()
scale = scaler.fit_transform(df_v2)

In [105]:
scale

array([[ 0.1809131 , -0.88252743, -0.43062779, ...,  0.55638614,
        -0.06861517,  1.13996356],
       [ 0.1809131 , -0.80318093, -0.90819777, ...,  0.53912936,
        -0.06861517,  1.13996356],
       [ 0.1809131 , -0.80318093, -0.90819777, ...,  0.53912936,
        -0.05014186,  1.13996356],
       ...,
       [ 0.2362567 ,  0.20565318,  0.85736399, ...,  0.12496664,
        -1.28785397, -0.87722103],
       [ 0.01488231,  0.70440263,  1.53753942, ...,  0.5046158 ,
         0.74421069, -0.87722103],
       [ 0.73434907, -0.0097159 ,  0.79947672, ...,  0.65992682,
         1.15062363, -0.87722103]])

In [111]:
# Dùng hàm PCA để thực hiện
k = 20
my_pca = PCA (n_components = k )
pca_scale = my_pca.fit_transform(scale)

In [112]:
scale.shape

(476, 167)

In [113]:
# Chiều của dữ liệu giảm còn 476x20
pca_scale.shape

(476, 20)